### ISSUE TITLE
Need a new boolean field named "validated" on the respondent table.  

### ISSUE THREAD

**Issue by rgwozdz** [Cadasta/cadasta-db#4]
Should default to "false"

**Comment by danielduhh** [comment]
If we're validating each individual response, this boolean field "validated" belongs in the response table

**Comment by danielduhh** [comment]
@rgwozdz You were right! Validated belongs in the respondent table. We are validating individual submissions not individual responses to questions.

**Comment by danielduhh** [comment]
fixed by https://github.com/Cadasta/cadasta-db/commit/7f1c525925c3be5aa986a7ca7ee6991dfc5547dc
